package io.appwrite.enums

import com.google.gson.annotations.SerializedName

enum class Scopes(val value: String) {
    @SerializedName("sessions.write")
    SESSIONS_WRITE("sessions.write"),
    @SerializedName("users.read")
    USERS_READ("users.read"),
    @SerializedName("users.write")
    USERS_WRITE("users.write"),
    @SerializedName("teams.read")
    TEAMS_READ("teams.read"),
    @SerializedName("teams.write")
    TEAMS_WRITE("teams.write"),
    @SerializedName("databases.read")
    DATABASES_READ("databases.read"),
    @SerializedName("databases.write")
    DATABASES_WRITE("databases.write"),
    @SerializedName("collections.read")
    COLLECTIONS_READ("collections.read"),
    @SerializedName("collections.write")
    COLLECTIONS_WRITE("collections.write"),
    @SerializedName("tables.read")
    TABLES_READ("tables.read"),
    @SerializedName("tables.write")
    TABLES_WRITE("tables.write"),
    @SerializedName("attributes.read")
    ATTRIBUTES_READ("attributes.read"),
    @SerializedName("attributes.write")
    ATTRIBUTES_WRITE("attributes.write"),
    @SerializedName("columns.read")
    COLUMNS_READ("columns.read"),
    @SerializedName("columns.write")
    COLUMNS_WRITE("columns.write"),
    @SerializedName("indexes.read")
    INDEXES_READ("indexes.read"),
    @SerializedName("indexes.write")
    INDEXES_WRITE("indexes.write"),
    @SerializedName("documents.read")
    DOCUMENTS_READ("documents.read"),
    @SerializedName("documents.write")
    DOCUMENTS_WRITE("documents.write"),
    @SerializedName("rows.read")
    ROWS_READ("rows.read"),
    @SerializedName("rows.write")
    ROWS_WRITE("rows.write"),
    @SerializedName("files.read")
    FILES_READ("files.read"),
    @SerializedName("files.write")
    FILES_WRITE("files.write"),
    @SerializedName("buckets.read")
    BUCKETS_READ("buckets.read"),
    @SerializedName("buckets.write")
    BUCKETS_WRITE("buckets.write"),
    @SerializedName("functions.read")
    FUNCTIONS_READ("functions.read"),
    @SerializedName("functions.write")
    FUNCTIONS_WRITE("functions.write"),
    @SerializedName("sites.read")
    SITES_READ("sites.read"),
    @SerializedName("sites.write")
    SITES_WRITE("sites.write"),
    @SerializedName("log.read")
    LOG_READ("log.read"),
    @SerializedName("log.write")
    LOG_WRITE("log.write"),
    @SerializedName("execution.read")
    EXECUTION_READ("execution.read"),
    @SerializedName("execution.write")
    EXECUTION_WRITE("execution.write"),
    @SerializedName("locale.read")
    LOCALE_READ("locale.read"),
    @SerializedName("avatars.read")
    AVATARS_READ("avatars.read"),
    @SerializedName("health.read")
    HEALTH_READ("health.read"),
    @SerializedName("providers.read")
    PROVIDERS_READ("providers.read"),
    @SerializedName("providers.write")
    PROVIDERS_WRITE("providers.write"),
    @SerializedName("messages.read")
    MESSAGES_READ("messages.read"),
    @SerializedName("messages.write")
    MESSAGES_WRITE("messages.write"),
    @SerializedName("topics.read")
    TOPICS_READ("topics.read"),
    @SerializedName("topics.write")
    TOPICS_WRITE("topics.write"),
    @SerializedName("subscribers.read")
    SUBSCRIBERS_READ("subscribers.read"),
    @SerializedName("subscribers.write")
    SUBSCRIBERS_WRITE("subscribers.write"),
    @SerializedName("targets.read")
    TARGETS_READ("targets.read"),
    @SerializedName("targets.write")
    TARGETS_WRITE("targets.write"),
    @SerializedName("rules.read")
    RULES_READ("rules.read"),
    @SerializedName("rules.write")
    RULES_WRITE("rules.write"),
    @SerializedName("migrations.read")
    MIGRATIONS_READ("migrations.read"),
    @SerializedName("migrations.write")
    MIGRATIONS_WRITE("migrations.write"),
    @SerializedName("vcs.read")
    VCS_READ("vcs.read"),
    @SerializedName("vcs.write")
    VCS_WRITE("vcs.write"),
    @SerializedName("assistant.read")
    ASSISTANT_READ("assistant.read"),
    @SerializedName("tokens.read")
    TOKENS_READ("tokens.read"),
    @SerializedName("tokens.write")
    TOKENS_WRITE("tokens.write");

    override fun toString() = value
}