package io.appwrite.enums

import com.google.gson.annotations.SerializedName

enum class Scopes(val value: String) {
    @SerializedName("project.read")
    PROJECT_READ("project.read"),
    @SerializedName("project.write")
    PROJECT_WRITE("project.write"),
    @SerializedName("keys.read")
    KEYS_READ("keys.read"),
    @SerializedName("keys.write")
    KEYS_WRITE("keys.write"),
    @SerializedName("platforms.read")
    PLATFORMS_READ("platforms.read"),
    @SerializedName("platforms.write")
    PLATFORMS_WRITE("platforms.write"),
    @SerializedName("mocks.read")
    MOCKS_READ("mocks.read"),
    @SerializedName("mocks.write")
    MOCKS_WRITE("mocks.write"),
    @SerializedName("policies.read")
    POLICIES_READ("policies.read"),
    @SerializedName("policies.write")
    POLICIES_WRITE("policies.write"),
    @SerializedName("project.policies.read")
    PROJECT_POLICIES_READ("project.policies.read"),
    @SerializedName("project.policies.write")
    PROJECT_POLICIES_WRITE("project.policies.write"),
    @SerializedName("templates.read")
    TEMPLATES_READ("templates.read"),
    @SerializedName("templates.write")
    TEMPLATES_WRITE("templates.write"),
    @SerializedName("oauth2.read")
    OAUTH2_READ("oauth2.read"),
    @SerializedName("oauth2.write")
    OAUTH2_WRITE("oauth2.write"),
    @SerializedName("users.read")
    USERS_READ("users.read"),
    @SerializedName("users.write")
    USERS_WRITE("users.write"),
    @SerializedName("sessions.read")
    SESSIONS_READ("sessions.read"),
    @SerializedName("sessions.write")
    SESSIONS_WRITE("sessions.write"),
    @SerializedName("teams.read")
    TEAMS_READ("teams.read"),
    @SerializedName("teams.write")
    TEAMS_WRITE("teams.write"),
    @SerializedName("databases.read")
    DATABASES_READ("databases.read"),
    @SerializedName("databases.write")
    DATABASES_WRITE("databases.write"),
    @SerializedName("tables.read")
    TABLES_READ("tables.read"),
    @SerializedName("tables.write")
    TABLES_WRITE("tables.write"),
    @SerializedName("columns.read")
    COLUMNS_READ("columns.read"),
    @SerializedName("columns.write")
    COLUMNS_WRITE("columns.write"),
    @SerializedName("indexes.read")
    INDEXES_READ("indexes.read"),
    @SerializedName("indexes.write")
    INDEXES_WRITE("indexes.write"),
    @SerializedName("rows.read")
    ROWS_READ("rows.read"),
    @SerializedName("rows.write")
    ROWS_WRITE("rows.write"),
    @SerializedName("collections.read")
    COLLECTIONS_READ("collections.read"),
    @SerializedName("collections.write")
    COLLECTIONS_WRITE("collections.write"),
    @SerializedName("attributes.read")
    ATTRIBUTES_READ("attributes.read"),
    @SerializedName("attributes.write")
    ATTRIBUTES_WRITE("attributes.write"),
    @SerializedName("documents.read")
    DOCUMENTS_READ("documents.read"),
    @SerializedName("documents.write")
    DOCUMENTS_WRITE("documents.write"),
    @SerializedName("buckets.read")
    BUCKETS_READ("buckets.read"),
    @SerializedName("buckets.write")
    BUCKETS_WRITE("buckets.write"),
    @SerializedName("files.read")
    FILES_READ("files.read"),
    @SerializedName("files.write")
    FILES_WRITE("files.write"),
    @SerializedName("tokens.read")
    TOKENS_READ("tokens.read"),
    @SerializedName("tokens.write")
    TOKENS_WRITE("tokens.write"),
    @SerializedName("functions.read")
    FUNCTIONS_READ("functions.read"),
    @SerializedName("functions.write")
    FUNCTIONS_WRITE("functions.write"),
    @SerializedName("executions.read")
    EXECUTIONS_READ("executions.read"),
    @SerializedName("executions.write")
    EXECUTIONS_WRITE("executions.write"),
    @SerializedName("execution.read")
    EXECUTION_READ("execution.read"),
    @SerializedName("execution.write")
    EXECUTION_WRITE("execution.write"),
    @SerializedName("sites.read")
    SITES_READ("sites.read"),
    @SerializedName("sites.write")
    SITES_WRITE("sites.write"),
    @SerializedName("log.read")
    LOG_READ("log.read"),
    @SerializedName("log.write")
    LOG_WRITE("log.write"),
    @SerializedName("providers.read")
    PROVIDERS_READ("providers.read"),
    @SerializedName("providers.write")
    PROVIDERS_WRITE("providers.write"),
    @SerializedName("topics.read")
    TOPICS_READ("topics.read"),
    @SerializedName("topics.write")
    TOPICS_WRITE("topics.write"),
    @SerializedName("subscribers.read")
    SUBSCRIBERS_READ("subscribers.read"),
    @SerializedName("subscribers.write")
    SUBSCRIBERS_WRITE("subscribers.write"),
    @SerializedName("targets.read")
    TARGETS_READ("targets.read"),
    @SerializedName("targets.write")
    TARGETS_WRITE("targets.write"),
    @SerializedName("messages.read")
    MESSAGES_READ("messages.read"),
    @SerializedName("messages.write")
    MESSAGES_WRITE("messages.write"),
    @SerializedName("rules.read")
    RULES_READ("rules.read"),
    @SerializedName("rules.write")
    RULES_WRITE("rules.write"),
    @SerializedName("webhooks.read")
    WEBHOOKS_READ("webhooks.read"),
    @SerializedName("webhooks.write")
    WEBHOOKS_WRITE("webhooks.write"),
    @SerializedName("locale.read")
    LOCALE_READ("locale.read"),
    @SerializedName("avatars.read")
    AVATARS_READ("avatars.read"),
    @SerializedName("health.read")
    HEALTH_READ("health.read"),
    @SerializedName("assistant.read")
    ASSISTANT_READ("assistant.read"),
    @SerializedName("migrations.read")
    MIGRATIONS_READ("migrations.read"),
    @SerializedName("migrations.write")
    MIGRATIONS_WRITE("migrations.write"),
    @SerializedName("schedules.read")
    SCHEDULES_READ("schedules.read"),
    @SerializedName("schedules.write")
    SCHEDULES_WRITE("schedules.write"),
    @SerializedName("vcs.read")
    VCS_READ("vcs.read"),
    @SerializedName("vcs.write")
    VCS_WRITE("vcs.write"),
    @SerializedName("presences.read")
    PRESENCES_READ("presences.read"),
    @SerializedName("presences.write")
    PRESENCES_WRITE("presences.write"),
    @SerializedName("backups.policies.read")
    BACKUPS_POLICIES_READ("backups.policies.read"),
    @SerializedName("backups.policies.write")
    BACKUPS_POLICIES_WRITE("backups.policies.write"),
    @SerializedName("archives.read")
    ARCHIVES_READ("archives.read"),
    @SerializedName("archives.write")
    ARCHIVES_WRITE("archives.write"),
    @SerializedName("restorations.read")
    RESTORATIONS_READ("restorations.read"),
    @SerializedName("restorations.write")
    RESTORATIONS_WRITE("restorations.write"),
    @SerializedName("domains.read")
    DOMAINS_READ("domains.read"),
    @SerializedName("domains.write")
    DOMAINS_WRITE("domains.write"),
    @SerializedName("events.read")
    EVENTS_READ("events.read");

    override fun toString() = value
}